builds:
  - binary: n400
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: n400
    homepage: https://github.com/thientran2020/n400
    tap:
      owner: thientran2020
      name: homebrew-thientran2020
    commit_author:
      name: thientran
      email: thienytran14@gmail.com

checksum:
  name_template: 'checksums.txt'